# config.yaml
neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"


llm:
 model: "qwen-turbo"   
 temperature: 0.3
 max_tokens: 1500

truncate:
  max_experiments: 5

context:
  expiry_seconds: 3600  
